# Generated by Django 3.1.1 on 2020-09-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('telefon', models.IntegerField()),
                ('bilgi', models.CharField(blank=True, max_length=30)),
                ('cinsiyet', models.CharField(choices=[('erkek', 'Erkek'), ('kadın', 'Kadın')], max_length=50)),
                ('ekl_tarih', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(blank=True, upload_to='resimler/')),
            ],
        ),
    ]
