# Generated by Django 3.1.1 on 2020-09-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ad',
            new_name='isim',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='soyad',
            new_name='soyisim',
        ),
    ]
