# Generated by Django 3.1.1 on 2020-10-26 04:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_etiket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('erkek', 'Erkek'), ('kadın', 'Kadın')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='etiket',
            field=models.CharField(blank=True, choices=[('is', 'İş'), ('okul', 'Okul'), ('arkadas', 'Arkadaş'), ('aile', 'Aile')], default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='foto',
            field=models.ImageField(blank=True, help_text='jpg,png,bmp', upload_to='resimler/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telefon',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='0', max_length=128, region=None),
        ),
    ]
