# Generated by Django 3.1.1 on 2020-11-04 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20201026_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='foto',
            field=models.ImageField(blank=True, help_text='jpg,png,bmp resim yükleyebilirsiniz', upload_to='resimler/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telefon',
            field=models.CharField(blank=True, default='00', max_length=30),
        ),
    ]
